# Copyright 2022 Wmbat
# 
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
# 
#     http://www.apache.org/licenses/LICENSE-2.0
# 
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

intf_libs = # Interface dependencies.
import intf_libs += range-v3%lib{range-v3}

impl_libs = # Implementation dependencies.
import impl_libs += glfw%lib{glfw}

lib{common}: {hxx ixx txx cxx}{** -version} hxx{version} $impl_libs $intf_libs

hxx{version}: in{version} $src_root/manifest

hxx{export}@./: cxx.importable = false

# Build options.
#
cxx.poptions =+ "-I$out_root" "-I$src_root"

{hbmia obja}{*}: cxx.poptions += -DLIBCOMMON_STATIC_BUILD
{hbmis objs}{*}: cxx.poptions += -DLIBCOMMON_SHARED_BUILD

# Export options.
#
lib{common}:
{
  cxx.export.poptions = "-I$out_root" "-I$src_root"
  cxx.export.libs = $intf_libs
}

liba{common}: cxx.export.poptions += -DLIBCOMMON_STATIC
libs{common}: cxx.export.poptions += -DLIBCOMMON_SHARED

# For pre-releases use the complete version to make sure they cannot be used
# in place of another pre-release or the final version. See the version module
# for details on the version.* variable values.
#
if $version.pre_release
  lib{common}: bin.lib.version = "-$version.project_id"
else
  lib{common}: bin.lib.version = "-$version.major.$version.minor"

# Install into the libcommon/ subdirectory of, say, /usr/include/
# recreating subdirectories.
#
{hxx ixx txx}{*}:
{
  install         = include/libcommon/
  install.subdirs = true
}
